# Generated by Django 5.0 on 2024-11-26 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('f_name', models.CharField(max_length=150, null=True)),
                ('l_name', models.CharField(max_length=150, null=True)),
                ('age', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('group', models.ManyToManyField(null=True, related_name='user', to='apis.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Attendens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(null=True)),
                ('attended_time', models.DateTimeField(blank=True, null=True)),
                ('missed_time', models.DateTimeField(blank=True, null=True)),
                ('timeout_time', models.DateTimeField(blank=True, null=True)),
                ('come', models.BooleanField(default=False, null=True)),
                ('gone', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendens', to='apis.users')),
            ],
        ),
    ]
